[package]
name = "darkestdev/darkocomm"
description = "A BridgeNet2-based implementation similar to sleitnick's Comm, designed to replace it for Knit."
version = "1.0.6"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BridgeNet2 = "darkestdev/bridgenet2@1.0.2"
